apiVersion: v2
name: prometheus
description: my helm chart for prometheus monitoring retrieval app

type: application

version: 0.1.0
appVersion: "1.0.0"

maintainers:
- email: manpham130699@gmail.com
  name: manpham
